---
- include_tasks: "preflight.yml"

- name: "Checkout homer assets"
  ansible.builtin.git:
    repo: "{{ homer_docker__assets_git_repo_url }}"
    dest: "{{ homer_docker__assets_dir }}"

- name: "Deploy homer service file"
  template:
    src: "homer.service.j2"
    dest: "/etc/systemd/system/homer.service"
  notify: "Restart homer"
